### ISSUE TITLE
Not loading module

### ISSUE THREAD

**Issue by DickSwart** [finity69x2/cover-control-button-row#1]
First off thanks for this, I've been waiting for something like this for a while.
I Installed the module through HACS and I added the module to Lovelace
```yaml
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/cover-control-button-row/cover-control-button-row.js
      type: module
```
But I still get a message _Custom element doesn't exist: cover-position-preset-row._

Help would be appreciated.
